services:
  mengxu-readme:
    container_name: website
    image: mengxu-readme-website
    build: .
    # uncomment these if you are having this issue with the build:
    # /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
    # and fill the args values with the output of the commands on the right
    # build:
    #   args:
    #     GROUPID: # id -g
    #     GROUPNAME: # id -gn
    #     USERID: # id -u
    #     USERNAME: # echo $USER
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s
