version: "3"
services:
  mengxu-readme:
    container_name: website
    image: mengxu-readme-website
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 15s

  html-proofer:
    container_name: html-proofer
    image: klakegg/html-proofer
    volumes:
      - ./_site:/site
    command: ["/site", "--http-status-ignore", "999"]
    depends_on:
      mengxu-readme:
        condition: service_healthy
